### ISSUE TITLE
Broken videos are uploaded to S3

### ISSUE THREAD

**Issue by kolodiy** [aerokube/moon#100]
In some cases, an internal error occurs and the broken video file is uploaded to S3, here are the sample logs:

frame= 1094 fps= 12 q=26.0 size=     512kB time=00:01:26.25 b2018-12-04T16:42:45.748733546Z sh: can't kill pid 26: No such process
/video.mp4 -> s3/moon-test-bucket/chrome-70-0-ae0a88f6-46f2-481b-82f1-4df01af79bd8/video.mp4
Total: 768.05 KB, Transferred: 768.05 KB, 

Speed: 6.51 MB/s
itrate=  48.6kbits/s speed=0.948x    
frame= 1100 fps= 12 q=26.0 size=     512kB time=00:01:26.75 bitrate=  48.4kbits/s speed=0.948x    
frame= 1107 fps= 12 q=26.0 size=     512kB time=00:01:27.33 bitrate=  48.0kbits/s speed=0.948x    
frame= 1113 fps= 12 q=26.0 size=     512kB time=00:01:27.83 bitrate=  47.8kbits/s speed=0.949x    
frame= 1120 fps= 12 q=26.0 size=     512kB time=00:01:28.41 bitrate=  47.4kbits/s speed=0.949x    
frame= 1127 fps= 12 q=26.0 size=     512kB time=00:01:29.00 bitrate=  47.1kbits/s speed=0.949x    
frame= 1134 fps= 12 q=26.0 size=     512kB time=00:01:29.58 bitrate=  46.8kbits/s speed=0.95x    
frame= 1140 fps= 12 q=26.0 size=     512kB time=00:01:30.08 bitrate=  46.6kbits/s speed=0.95x    
frame= 1146 fps= 12 q=26.0 size=     512kB time=00:01:30.58 bitrate=  46.3kbits/s speed=0.95x

**Comment by vania-pooh** [comment]
@kolodiy accepted for the next release.

**Comment by savvagen** [comment]
Video recording is working fine with configurations. 
dc.setCapability("videoFrameRate", 20)
dc.setCapability("videoCodec", "mpeg4")
The problem may be is in the frame rate - it should be more than 20 ...

**Comment by kolodiy** [comment]
@vania-pooh, is there any update on this issue?
@savvagen -  in our case issue persists even with setting those configs.

**Comment by vania-pooh** [comment]
@kolodiy working on this issue right now.

**Comment by vania-pooh** [comment]
Still reproducing in AWS because of ffmpeg segfaults.

**Comment by vania-pooh** [comment]
Several reasons of the issue:
1) Uploading should be done only when `ffmpeg` has finished working.
2) FFMpeg has a segfault in this line: https://github.com/FFmpeg/FFmpeg/blob/4154f8967820ca734a77ce91bb590cd77649dee8/libavdevice/xcbgrab.c#L424 The main workaround is to turn off mouse cursor with `-draw_mouse 0` flag.
3) Also could be caused by not matching number of CPU and real CPU limit caused by virtualization and Kubernetes limit. Main solution is adding `-threads 1` flag to both `ffmpeg` decoder and encoder (before and after `-i` flag).
