### ISSUE TITLE
Freezing pods

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/moon#146]
```
kubectl -n moon logs chrome-73-0-f53a35d9-bcf6-4af7-af66-9491e0a83343 -c defender
2019/05/17 21:26:15 Unsolicited response received on idle HTTP channel starting with "unknown command: "; err=<nil>
```

**Comment by vania-pooh** [comment]
This error means a response was received but no request was sent.

**Comment by vania-pooh** [comment]
Fixed in aerokube/moon-src@e3586cbdb3492d77d48242a6c4696e1e11d3bb05.

**Comment by z-aliakseyeu** [comment]
@vania-pooh Hello!
Could you please help to understand the root cause of that issue and how was it fixed? Because we are facing currently very similar issue.
Here are few details, which probably could help to understand whether it's a similar issues.
Kubernetes cluster version `1.14.10-gke.42`
The following versions of moon containers are running:
```
aerokube/moon:1.6.0
aerokube/moon-api:1.5.1
aerokube/selenoid-ui:1.10.0
```
We are having in quite big amount of browsers containers with the following error in logs:
```
2020/07/30 12:02:01 Unsolicited response received on idle HTTP channel starting with "{\"value\":{\"error\":\"unknown command\",\"message\":\"unknown command: unknown command: \",\"stacktrace\":\"#0 0x5585857a6189 \\u003Cunknown>\\n\"}}"; err=<nil>
```
All of those containers with error above already closed the browser and just hanging doing nothing.
Is there any trick around to fix it or tips how to debug the root cause of the issue?

Thank you

**Comment by vania-pooh** [comment]
@z-aliakseyeu 
1) Update `moon` and `moon-api` to latest release 1.6.1.
2) Take a look at this checklist: https://aerokube.com/moon/latest/#_moon_checklist

**Comment by z-aliakseyeu** [comment]
@vania-pooh thank you for the advices!
Updating the version is achievable pretty easy, however the second thing (especially updating configmap for coredns). In GKE cluster this config map in namespace kube-system doesn't exist. There are only those config maps and their content is quite different from the one in documentation:
```
kube-dns | Config Map | kube-system | general |  
kube-dns-autoscaler | Config Map | kube-system | general
```
There are following config maps with `dns` in name available in `kube-system` namespace.
Could you please help to understand where it could be changed in that situation?

**Comment by vania-pooh** [comment]
@z-aliakseyeu don't need to fix DNS in case of kube-dns.
