### ISSUE TITLE
[BUG] [PW 1.16.3] [Chromium] Error: Target page, context or browser has been closed

### ISSUE THREAD

**Issue by dipiash** [aerokube/moon#299]
Hi there! I need some help, to run and pass tests. In this [thread](https://github.com/microsoft/playwright/issues/10552#issuecomment-980037457) I got recommendations to open issue in this repo. I also created [issue](https://github.com/codeceptjs/CodeceptJS/issues/3155) in CodeceptJs repo.

#### What are you trying to achieve?
Simple launching a browser. Navigating to a page. Find selector. Close browser.

Tests was start for the same page: https://dasreda.ru/

#### What do you get instead?
**Local**: browser launch, navigate to page, find the selector, pass test, close browser.
   - Success (Local) - [local-moon-log.log](https://github.com/microsoft/playwright/files/7608293/local-moon-log.log)

Local test pass. Remote test (on the https://aerokube.com/moon/) fail because can't wait when page loaded.

**Remote**: browser launch, navigate page... Infinite loading... Crush with error: `Error: Target page, context or browser has been closed`
   - Error (Remote) - [remote-moon-log.log](https://github.com/microsoft/playwright/files/7608294/remote-moon-log.log)

### Details
Playwright Version: 1.16.3  (the same behavior on 1.8.0)
Operating System: *nix
Node.js version: v14.18.1
Browser: chromium
Extra: codeceptjs (3.0.4 / the same behavior on 3.1.3)

EXAMPLE: https://github.com/dipiash/codecept-playwrite-bug-report

**Comment by vania-pooh** [comment]
@dipiash usually infinite loading means missing firewall rules from the network where browsers are running (Kubernetes cluster network) to the network where you app is running. You can run a manual session from Moon UI and try to reproduce the same sequence of steps in the UI. If there is an issue with firewalls you will see the same behavior. Manual sessions are behind the scenes using Selenium to start and this will be a clear signal, that this issue is not related to Playwright.

**Comment by dipiash** [comment]
We were found a problem. In our config we have a shared resources in a Kubernetes for moon. When we start container with tests in parallel resources were divided and browser crashed because there was not enough RAM.

After change this [part of config](https://github.com/aerokube/charts/blob/master/moon/values.yaml#L351-L360)  everything is fine.
