### ISSUE TITLE
moon doesn't spawn all the browser pods that it should

### ISSUE THREAD

**Issue by johnqa** [aerokube/moon#341]
I am running moon and I have noticed it never spawned more than 16 browser pods out of 30 that corresponds to the license. 
I have set the resourcequotas to 32.

I am running selenium tests from a linux server.

What can the issue be and how can I debug this?

Thank you!

**Comment by vania-pooh** [comment]
@johnqa to debug this I would list browser pods and see whether some of them remain in `Pending` state for a long time.
```
$ kubectl get po -n moon
```
If that's the case - simply describe pod detailed information:

```
kubectl describe po chrome-XXXXXX -n moon
```
There should be the reason why it not starting. The most frequent reason is insufficient computing resources (CPUs, memory). Sometimes this is also because of some taints added to Kubernetes nodes - in that case you need to [configure tolerations](https://aerokube.com/moon/latest/#tolerations) in Moon settings.

**Comment by johnqa** [comment]
In the end it was a problem with nunit tests used to run selenium tests, as they had set the number of parallel threads to 16. Changing that got full load of moon.
