### ISSUE TITLE
Add ability to upload videos only when test fails

### ISSUE THREAD

**Issue by facusantillo** [aerokube/moon#343]
Currently, all videos are uploaded to S3 storage. If the suite contains 1k+ tests, you won't likely be interested in all the tests but the ones who fail.

This feature would enable us to be more efficient with our S3 storage overall.

I think that maybe we can achieve it by communicating the test status from the container to the video container to make the choice to upload it or not.

**Comment by vania-pooh** [comment]
@facusantillo This is not possible, because Moon is just an API to start browsers. Moon even does not know that you are running tests. Our recommended approach is running all tests without video recording and then rerun failed test cases with video recording enabled. Otherwise every parallel browser session with video recording consumes +1 CPU and +1 GB RAM and this is too expensive.
