### ISSUE TITLE
Automatically select client certificate in Chrome

### ISSUE THREAD

**Issue by cr-liorholtzman** [aerokube/moon#373]
The company I'm working in is currently considering using Moon to replace Zalenium since it's not possible to use client-certificate when working with Zalenium 

To work with a client certificate and use chrome, it is required to import it to the pod and also set  "AutoSelectCertificateForUrls".
Is it something we can do using Moon? even if it means setting some specific environment variables?

**Comment by aandryashin** [comment]
Hello, currently only servers CA can be imported to pod:
https://aerokube.com/moon/latest/#ca-certs

We will consider implementation of mutual client TLS authentication for
browser in further releases.

ср, 8 мар. 2023 г. в 12:16, cr-liorholtzman ***@***.***>:

**Comment by aandryashin** [comment]
Hello, after deeper investigation, i have found that client mutual TLS
authentication only requires client cert and key installed in browser
profile, that is already implemented in Moon, how to upload custom browser
profile to moons browser pod you can find here:

https://blog.aerokube.com/selenium-moon-environment-provisioning-72402242c917

ср, 8 мар. 2023 г. в 12:41, Alexander Andryashin ***@***.***>:

**Comment by slunyaak** [comment]
Hi, 
uploading new profile in Moon pod works. But the question is how to add into profile client certificate. I have tried following: I started Moon Chrome browser, imported in it required client certificate for mutual TLS authentication and then downloaded profile. After that I followed instruction from Moon documentation in order to upload custom Chrome profile. I did make sure, that upload of new profile was successful. Unfortunately  this solution did not worked. The client certificate was not present in the Moon browser after profile upload. After that I investigated that subject a little bit and I found that client certificates aren't normally  stored in Chrome profile, but in host OS. So could you please advise, how to make working following solution "client mutual TLS authentication only requires client cert and key installed in browser profile"?

Thank you

**Comment by aandryashin** [comment]
Have you added chrome argument --user-data-dir to point to your custom
profile?

чт, 2 мая 2024 г. в 10:29, slunyaak ***@***.***>:

**Comment by slunyaak** [comment]
Yes, I have added it, this is used code:

       ChromeOptions options = new ChromeOptions();

        options.setCapability("moon:options", Map.of("context", "http://WWeebbHHoosstt/profile.tar.gz"));

        options.addArguments("--user-data-dir=/home/user/profile");
        try {
            WebDriver driver = new RemoteWebDriver(new URL("http://MMoonnHHoosstt/wd/hub"), options);
        } catch (MalformedURLException e){

        }

**Comment by aandryashin** [comment]
Hello!

After installing the certificate in the browser you have to download not a
profile and /home/user/.pki directory that will contain your installed
certificate, then you can upload it to moon pod using moon context feature.
Sorry for the confusion. Actually context allows you to upload any custom
user's configuration.

чт, 2 мая 2024 г. в 16:15, slunyaak ***@***.***>:

**Comment by slunyaak** [comment]
Hi, thank you!, Uploading  /home/user/.pki with imported client certificate using Moon context feature was the right solution.

**Comment by vania-pooh** [comment]
@slunyaak so this is now resolved, right?

**Comment by slunyaak** [comment]
@vania-pooh Hi, uploading certificate works perfectly, thanks! But now we are facing new issue with confirming certificate selection in Chrome browser running in Moon. We have imported there just one certificate , but we have issue making Selenide to click on "OK" button in order to confirm certificate selection. We have tried to resolve that by  defaulting certificate using AutoSelectCertificateForUrls, but required directories for storing auto_select_certificate.json in pod cannot be located. Could you please advice, how to solve it?

**Comment by vania-pooh** [comment]
@slunyaak this seems to be your project specific issue. Please provide more details on what should be clicked, e.g. a screenshot.

**Comment by slunyaak** [comment]
So this is screenshot from test, where I am required to confirm certificate selection in Moon's Chrome: 
![image](https://github.com/user-attachments/assets/bede59a6-6cea-463f-9f68-c065d3c51747)

**Comment by vania-pooh** [comment]
@aandryashin any ideas?

**Comment by aandryashin** [comment]
Ihmo you should be able to click on this button using selenium.

ср, 21 авг. 2024 г., 13:02 Ivan Krutov ***@***.***>:

**Comment by slunyaak** [comment]
My colleague has unsuccessfully tried couple of these following approaches:

A.
Selenide.confirm("OK");

B.
Selenide.confirm();

C.
Selenide.switchTo().alert().accept();

D.
RobotWriter robotWriter = new RobotWriter();
robotWriter.tab();
robotWriter.tab();
robotWriter.tab();
robotWriter.enter();

What is please your suggestion?

**Comment by aandryashin** [comment]
Try to use plain selenium instead of selenide.

ср, 21 авг. 2024 г., 13:31 slunyaak ***@***.***>:

**Comment by phillwhite** [comment]
We've tried to use the Actions class from Selenium for pressing the TAB and ENTER keys to confirm the popup, but without success. From several discussions on Stackoverflow, it seems to me that this is an OS popup and therefore it cannot be confirmed even using pure Selenium. Do you have any other suggestions for us @aandryashin?

**Comment by aandryashin** [comment]
We will check it and update you.

пн, 2 сент. 2024 г., 10:56 phillwhite ***@***.***>:

**Comment by aandryashin** [comment]
After investigation we have found the way to auto select client
certificates in the chrome browser. We have added capability to turn it on,
this feature will be available in the next release.

Alexander Andryashin.

пн, 2 сент. 2024 г. в 12:21, Alexander Andryashin ***@***.***>:

**Comment by vania-pooh** [comment]
Need to document `autoSelectClientCerts=true` capability and Firefox pref value.

**Comment by aandryashin** [comment]
Hello,

The feature is released in 2.7.2, please check it:

https://aerokube.com/moon/latest/#capability-auto-select-client-certs

чт, 5 сент. 2024 г. в 22:01, Alexander Andryashin ***@***.***>:
